### ISSUE TITLE
表記ゆれ「巻上げ」を「巻き上げ」に統一する

### ISSUE THREAD

**Issue by suin** [yytypescript/book#153]
- 「巻上げ」となっているところを「巻き上げ」に書き換える
- prhに「巻き上げ」を追加する

**Comment by theMistletoe** [comment]
> prhに「巻き上げ」を追加する

こちら、yytypescript.ymlに以下の設定を追記してtextlintからサジェストされるようにする、という理解であっていますか？

```yml
- expected: 巻き上げ
    patterns:
      - 巻上げ
```
