### ISSUE TITLE
「Reactでいいねボタンを作ろう」でCSSを追加したときに、サンプルのようにブラウザの中央に表示されるようにしませんか？

### ISSUE THREAD

**Issue by nissyi-gh** [yytypescript/book#770]
# 何をどうしたいか？

[Reactでいいねボタンを作ろう#ボタンのビジュアルを作り込む](https://typescriptbook.jp/tutorials/react-like-button-tutorial#%E3%83%9C%E3%82%BF%E3%83%B3%E3%81%AE%E3%83%93%E3%82%B8%E3%83%A5%E3%82%A2%E3%83%AB%E3%82%92%E4%BD%9C%E3%82%8A%E8%BE%BC%E3%82%80)で掲載されているCSSに数行追加して、サンプル画像のようにブラウザ中央にボタンが表示されるようにしたいです。

## サンプル画像

https://typescriptbook.jp/assets/images/screen3-3b3d3442391731495600e8e718c9dcf8.png

![image](https://github.com/yytypescript/book/assets/81596063/3d0515ff-ea84-4c39-a734-01f0ec255cb9)

# そうしたい理由は何か？

[Reactでいいねボタンを作ろう#ボタンのビジュアルを作り込む](https://typescriptbook.jp/tutorials/react-like-button-tutorial#%E3%83%9C%E3%82%BF%E3%83%B3%E3%81%AE%E3%83%93%E3%82%B8%E3%83%A5%E3%82%A2%E3%83%AB%E3%82%92%E4%BD%9C%E3%82%8A%E8%BE%BC%E3%82%80)で、掲載されているCSSを[App.cssの最後に追加](https://typescriptbook.jp/tutorials/react-like-button-tutorial#%E3%83%9C%E3%82%BF%E3%83%B3%E3%81%AE%E3%83%93%E3%82%B8%E3%83%A5%E3%82%A2%E3%83%AB%E3%82%92%E4%BD%9C%E3%82%8A%E8%BE%BC%E3%82%80:~:text=App.css%E3%81%AE%E6%9C%80%E5%BE%8C%E3%81%AB%E8%BF%BD%E5%8A%A0%E3%81%97%E3%81%A6%E3%81%8F%E3%81%A0%E3%81%95%E3%81%84%E3%80%82)しました。ボタン自体のスタイルは綺麗にあたるのですが、画面上部に表示されてしまい少し見づらいので、サンプル画像のように画面中央部に表示されると見えやすいのではないかと考えています。

```css
.likeButton {
  background-color: rgb(231, 76, 60);
  color: white;
  padding: 0.8rem;
  border-radius: 0.4rem;
  cursor: pointer;
}
```

<img width="719" alt="image" src="https://github.com/yytypescript/book/assets/81596063/0ddb46ae-9aba-4e6d-8ac7-d8b6417261e3">

## CSS追加案

```css
.likeButton {
  background-color: rgb(231, 76, 60);
  color: white;
  padding: 0.8rem;
  border-radius: 0.4rem;
  cursor: pointer;
  /* 以下を追加 */
  position: fixed;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
```
<img width="719" alt="fix_image" src="https://github.com/yytypescript/book/assets/81596063/b0636c48-5de0-4dd1-91dc-c6aab0c8dc6a">

# やるとなったら自分が担当したいか？

ぜひPRを立てたいです。
